# Generated by Django 5.0.6 on 2024-08-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0002_remove_booking_booking_time_remove_seat_is_available_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='vailable_seats',
        ),
        migrations.AddField(
            model_name='train',
            name='available_seats',
            field=models.IntegerField(default=10),
        ),
    ]
